

CREATE DATABASE g05com2900
GO

USE g05com2900
GO

CREATE SCHEMA ddbba
GO

--Creamos las tablas: 
CREATE TABLE Ciudad 
(
    Ciudad_PK INT IDENTITY(1,1) NOT NULL, 
    Ciudad_Descrip VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (Ciudad_PK),
)
GO

CREATE TABLE Genero 
(
    Genero_PK INT IDENTITY(1,1) NOT NULL,  
    Genero_Descrip VARCHAR(100) NOT NULL,
    CONSTRAINT PK_GENERO PRIMARY KEY (Genero_PK),
)
GO

CREATE TABLE LineaDeProducto 
(
    LineaDeProducto_PK INT  IDENTITY(1,1) NOT NULL,  
    LineaDeProducto_Descrip VARCHAR(100) NOT NULL,
    CONSTRAINT PK_LINEA_PRODUCTOS PRIMARY KEY (LineaDeProducto_PK),
)
GO

CREATE TABLE Factura
(
    Factura_PK INT  IDENTITY(1,1) NOT NULL,  
    Factura_Descrip VARCHAR(100) NOT NULL,
    CONSTRAINT PK_FACTURA PRIMARY KEY (Factura_PK),
)
GO

CREATE TABLE MediosDePago
(
    MediosDePago_PK INT  IDENTITY(1,1) NOT NULL,  
    MediosDePago_Descrip VARCHAR(100) NOT NULL,
    CONSTRAINT PK_MEDIOS_DE_PAGO PRIMARY KEY (MediosDePago_PK),
)
GO

CREATE TABLE Sucursal
(
    Sucursal_PK INT  IDENTITY(1,1) NOT NULL,  
    Sucursal_Nombre  VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (Sucursal_PK),
)
GO

CREATE TABLE Productos 
(
    Productos_PK INT IDENTITY(1,1) NOT NULL, 
    Productos_Descrip VARCHAR(100) NOT NULL,
    Precio INT CHECK (Precio > 0),
    Linea_Producto_FK INT NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (Productos_PK),
    CONSTRAINT FK_PRODUCTOS FOREIGN KEY (Linea_Producto_FK) REFERENCES LineaDeProducto(LineaDeProducto_PK) 
)
GO


CREATE TABLE Clientes
(
    Clientes_PK INT IDENTITY(1,1) NOT NULL, 
    Clientes_Nombre VARCHAR(100) NOT NULL,
    Clientes_Apellido VARCHAR(100) NOT NULL,
    Genero_FK INT  NOT NULL,
    Ciudad_FK INT NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (Clientes_PK),
    CONSTRAINT FK_CLIENTES FOREIGN KEY (Genero_FK) REFERENCES Genero(Genero_PK),
    CONSTRAINT FK_CLIENTES2 FOREIGN KEY (Ciudad_FK) REFERENCES Ciudad(Ciudad_PK)
)
GO
